#!/usr/bin/env python3
"""Generate the embedded buff-duration catalog from the eqlwiki spell harvest.

Offline: reads spells.json and writes src/EQBuddy.Core/Data/BuffDurations.json —
the catalog behind buff countdown timers. A buff is any beneficial spell with a
documented duration of a minute or more and a cast-on-you landing line; the
tracker correlates a recent cast with the landing line (the mez pattern), starts
a countdown from the wiki duration, learns real durations from natural fades
(ranks and AAs lengthen them), and clears on the fade line.

Exclusions (each listed in buffs-report.md):
  - landing lines already claimed by SlowSpells.json, FadeMessages.json or the
    regen tick line: exact-match catalogs must partition the message space.
  - durations under 60s: a countdown that expires during its own cast is noise.
  - no cast-on-you message: nothing to anchor the timer to.

Outputs:
  ../../../src/EQBuddy.Core/Data/BuffDurations.json  - the catalog
  buffs-report.md                                    - summary + exclusions
"""

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
SPELLS = HERE / "spells.json"
FADES = HERE.parents[2] / "src" / "EQBuddy.Core" / "Data" / "FadeMessages.json"
SLOWS = HERE.parents[2] / "src" / "EQBuddy.Core" / "Data" / "SlowSpells.json"
REGENS = HERE.parents[2] / "src" / "EQBuddy.Core" / "Data" / "RegenSpells.json"
OUT = HERE.parents[2] / "src" / "EQBuddy.Core" / "Data" / "BuffDurations.json"
REPORT = HERE / "buffs-report.md"

MIN_DURATION = 60


def canonical(name: str) -> str:
    return name.replace("`", "'")


def main():
    spells = json.loads(SPELLS.read_text(encoding="utf-8"))
    fade_msgs = {e["message"].lower() for e in json.loads(FADES.read_text(encoding="utf-8"))}
    slow_msgs = {m["message"].lower() for m in json.loads(SLOWS.read_text(encoding="utf-8"))["messages"]}
    regen_msg = json.loads(REGENS.read_text(encoding="utf-8"))["message"].lower()
    claimed = fade_msgs | slow_msgs | {regen_msg}

    excluded = []
    by_message = {}
    for s in spells:
        if s.get("beneficial") is not True:
            continue
        name = canonical(s["name"])
        duration = s.get("duration_seconds") or 0
        msg = (s.get("msg_cast_on_you") or "").strip()
        if duration < MIN_DURATION:
            if duration and msg:
                excluded.append((name, f"duration {duration:0.0f}s < {MIN_DURATION}s"))
            continue
        if not msg:
            excluded.append((name, "no cast-on-you message on the wiki page"))
            continue
        if msg.lower() in claimed:
            excluded.append((name, f"landing line {msg!r} already claimed by another catalog"))
            continue
        group = by_message.setdefault(msg, {})
        old = group.get(name)
        rec = {"name": name, "durationSeconds": duration}
        if old:
            rec["durationSeconds"] = max(rec["durationSeconds"], old["durationSeconds"])
        group[name] = rec

    messages = []
    for msg, group in sorted(by_message.items()):
        cands = sorted(group.values(), key=lambda r: r["name"])
        label = cands[0]["name"] if len(cands) == 1 else None
        messages.append({
            "message": msg,
            "label": label or SharedLabel(msg, cands),
            "spells": cands,
        })

    catalog = {
        "comment": "Buff-duration catalog for buff countdown timers. Grouped by "
                   "cast-on-you landing line; the tracker resolves shared lines via "
                   "cast correlation and treats unresolved durations as estimates. "
                   "Generated by scripts/harvests/eqlwiki/buffs-harvest.py — "
                   "regenerate, never hand-edit. Exclusions in buffs-report.md.",
        "messages": messages,
    }
    OUT.write_text(json.dumps(catalog, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")

    n = sum(len(m["spells"]) for m in messages)
    shared = [m for m in messages if len(m["spells"]) > 1]
    lines = [
        "# Buff-duration catalog report", "",
        f"- {n} buffs across {len(messages)} landing lines ({len(shared)} shared)",
        "", "## Shared landing lines (cast correlation resolves; unresolved = est)", "",
    ]
    for m in sorted(shared, key=lambda m: -len(m["spells"]))[:20]:
        lines.append(f"- {m['message']!r}: {len(m['spells'])} spells")
    lines += ["", "## Excluded", ""]
    for name, reason in sorted(excluded):
        lines.append(f"- {name}: {reason}")
    REPORT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{n} buffs across {len(messages)} lines -> {OUT.name}")


def SharedLabel(msg: str, cands) -> str:
    """A display label for a shared line: the sentence itself, trimmed — 'You feel
    different.' IS how the player knows it, and any one spell name would be a guess."""
    return msg.rstrip(".!")


if __name__ == "__main__":
    main()
